//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPrescription.EntityFramework.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> HPrimaryMark { get; set; }
        public Nullable<int> DPrimaryMark { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string Status { get; set; }
        public int Id { get; set; }
    
        public virtual DoctorMaster DoctorMaster { get; set; }
        public virtual HospitalMaster HospitalMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
